# Generated by Django 3.1.7 on 2021-04-02 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Кейсы',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('fio', models.CharField(blank=True, max_length=120, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_in', models.DateTimeField(auto_now_add=True, null=True)),
                ('actions', models.ManyToManyField(blank=True, null=True, to='bot.Case')),
            ],
            options={
                'verbose_name': 'Пользователи телеграмм',
            },
        ),
        migrations.CreateModel(
            name='ServerWindows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('port', models.BigIntegerField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('case', models.ManyToManyField(blank=True, null=True, to='bot.Case')),
            ],
            options={
                'verbose_name': 'Сервера Виндовс',
                'verbose_name_plural': 'Сервера Виндовс',
            },
        ),
        migrations.CreateModel(
            name='ServerLinux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('port', models.BigIntegerField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('case', models.ManyToManyField(blank=True, null=True, to='bot.Case')),
            ],
            options={
                'verbose_name': 'Сервера Линукс',
                'verbose_name_plural': 'Сервера Линукс',
            },
        ),
        migrations.CreateModel(
            name='Mikrotik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('port', models.BigIntegerField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('case', models.ManyToManyField(blank=True, null=True, to='bot.Case')),
            ],
            options={
                'verbose_name': 'Микротики',
                'verbose_name_plural': 'Микротики',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('log', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
