# Generated by Django 3.1.7 on 2021-04-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210402_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи телеграмм', 'verbose_name_plural': 'Пользователи телеграмм'},
        ),
    ]
