# Generated by Django 3.1.7 on 2021-04-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20210402_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('chat_id', models.BigIntegerField()),
                ('contact', models.CharField(blank=True, max_length=250, null=True)),
                ('message', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
