# Generated by Django 3.1.7 on 2021-04-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='step',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
