# Generated by Django 3.1.7 on 2021-04-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_case_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='LinuxServer',
            field=models.ManyToManyField(blank=True, null=True, to='bot.ServerLinux'),
        ),
        migrations.AddField(
            model_name='user',
            name='Mikrotik',
            field=models.ManyToManyField(blank=True, null=True, to='bot.Mikrotik'),
        ),
        migrations.AddField(
            model_name='user',
            name='WinServer',
            field=models.ManyToManyField(blank=True, null=True, to='bot.ServerWindows'),
        ),
    ]
