# Generated by Django 3.1.7 on 2021-06-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20210419_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('port', models.BigIntegerField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('case', models.ManyToManyField(blank=True, null=True, to='bot.Case')),
                ('group', models.ManyToManyField(blank=True, null=True, to='bot.Group')),
            ],
            options={
                'verbose_name': 'Целевые системы и устройства',
                'verbose_name_plural': 'Целевые системы и устройства',
            },
        ),
        migrations.RemoveField(
            model_name='serverlinux',
            name='case',
        ),
        migrations.RemoveField(
            model_name='serverwindows',
            name='case',
        ),
        migrations.RemoveField(
            model_name='user',
            name='LinuxServer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Mikrotik',
        ),
        migrations.RemoveField(
            model_name='user',
            name='WinServer',
        ),
        migrations.DeleteModel(
            name='Mikrotik',
        ),
        migrations.DeleteModel(
            name='ServerLinux',
        ),
        migrations.DeleteModel(
            name='ServerWindows',
        ),
        migrations.AddField(
            model_name='user',
            name='target',
            field=models.ManyToManyField(blank=True, null=True, to='bot.Target'),
        ),
    ]
