# Generated by Django 3.1.7 on 2021-06-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20210618_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='case',
        ),
    ]
