# Generated by Django 3.1.7 on 2021-06-18 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_remove_target_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группы', 'verbose_name_plural': 'Группы'},
        ),
    ]
