# Generated by Django 3.1.7 on 2021-06-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20210618_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'Действия', 'verbose_name_plural': 'Действия'},
        ),
    ]
