# Generated by Django 3.1.7 on 2021-06-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20210618_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='bot.Group'),
        ),
    ]
