# Generated by Django 3.1.7 on 2021-06-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20210621_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='group',
        ),
        migrations.AddField(
            model_name='target',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.group'),
        ),
    ]
