# Generated by Django 3.1.7 on 2021-07-14 13:18

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20210714_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='target',
        ),
        migrations.AddField(
            model_name='user',
            name='target',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='org', chained_model_field='org', default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.target'),
            preserve_default=False,
        ),
    ]
