# Generated by Django 3.1.7 on 2021-07-14 13:48

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_auto_20210714_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='target',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='org', chained_model_field='org', null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.target'),
        ),
    ]
