# Generated by Django 3.1.7 on 2021-07-14 14:04

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_auto_20210714_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='target',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='org', chained_model_field='org', horizontal=True, null=True, to='bot.Target'),
        ),
    ]
