# Generated by Django 3.1.7 on 2021-07-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_auto_20210719_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='org',
        ),
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.ManyToManyField(blank=True, null=True, to='bot.Org'),
        ),
    ]
