# Generated by Django 3.1.7 on 2021-07-19 10:47

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0025_auto_20210719_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='actions',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='target', chained_model_field='group', horizontal=True, null=True, to='bot.Case'),
        ),
    ]
