# Generated by Django 3.1.7 on 2021-07-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0026_auto_20210719_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='actions',
            field=models.ManyToManyField(blank=True, null=True, to='bot.Case'),
        ),
    ]
