# Generated by Django 3.1.7 on 2021-07-19 15:04

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_auto_20210719_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='actions',
        ),
        migrations.AddField(
            model_name='target',
            name='case',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='group', chained_model_field='group', horizontal=True, null=True, to='bot.Case'),
        ),
    ]
