# Generated by Django 3.1.7 on 2021-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_auto_20210719_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CurrentHost',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
