# Generated by Django 3.1.7 on 2021-07-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_auto_20210722_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='script',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
