# Generated by Django 3.1.7 on 2021-07-22 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_auto_20210722_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.group'),
            preserve_default=False,
        ),
    ]
