# Generated by Django 3.1.7 on 2021-07-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0034_auto_20210728_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='cred',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='interface',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
