# Generated by Django 3.1.7 on 2021-07-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_auto_20210728_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='vpntype',
            field=models.CharField(choices=[('-', '-'), ('ovpn-client', 'ovpn-client'), ('ppp-client', 'ppp-client'), ('pptp-client', 'pptp-client'), ('sstp-client', 'sstp-client')], default='1', max_length=20),
        ),
    ]
