# Generated by Django 3.1.7 on 2021-07-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0036_target_vpntype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='vpntype',
            field=models.CharField(choices=[('-', '-'), ('ovpn-client', 'ovpn-client'), ('ppp-client', 'ppp-client'), ('pptp-client', 'pptp-client'), ('sstp-client', 'sstp-client')], default='-', max_length=20),
        ),
    ]
