# Generated by Django 3.1.7 on 2021-08-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0039_auto_20210731_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='visiblename',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
