# Generated by Django 3.1.7 on 2022-01-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0040_target_visiblename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='vpntype',
            field=models.CharField(choices=[('-', '-'), ('ovpn-client', 'ovpn-client'), ('ppp-client', 'ppp-client'), ('pptp-client', 'pptp-client'), ('sstp-client', 'sstp-client'), ('ipip', 'ipip')], default='-', max_length=20),
        ),
    ]
